/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.fazecast.jSerialComm.*;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.io.*;
import java.awt.*;

public class jTerminal extends javax.swing.JFrame {
    private SerialPort comPorts[];
    private int port=-1;
    private boolean echoON=true;
    public SerialPort comPort;
    
    // list COM ports and add to the ComPortMenu items in the menu bar
    public jTerminal() {
        initComponents();
                // get information on COM ports and display in TextArea
        String s = "List COM ports";
        comPorts = SerialPort.getCommPorts();
        if(comPorts.length<1)           // if no COM ports found exit
            {System.out.println("no COM ports found"); return;}
        // print list of COM ports, add to COMportMenu and attach event handler
        for (int i = 0; i < comPorts.length; i++)   { 
           System.out.println(s+=("\ncomPort[" + i + "] = " + comPorts[i].getDescriptivePortName()));
          /* JMenuItem comPort= new JMenuItem(comPorts[i].getDescriptivePortName());
             comPort.addActionListener(new java.awt.event.ActionListener() {
             @Override
             public void actionPerformed(java.awt.event.ActionEvent evt)  {
                 JMenuItem mItem = (JMenuItem) evt.getSource();
                 for (int i = 0; i < comPorts.length; i++)  
                    if(comPorts[i].getDescriptivePortName().equals(mItem.getText()))
                        { port=i; openCOMport(); break; }
                //System.out.println("event " + mItem.getText() + " " + offset);
                }
              });        
          COMportMenu.add(comPort);  // add to COMportMenu
      */    }
       TerminalTextArea.setText(s+"\n"); // display list of COM ports
       if(comPorts.length==1)            // if 1 COM port found open it
            {port=0; openCOMport();}
       else
           TerminalTextArea.append("\nUse COM port menu to select serial port\n");
        //{port=1; openCOMport();}
    }
    
    // attempt to open COM port - if OK add data listener
    private boolean CanbusData=false;
    void openCOMport() {
        comPort = SerialPort.getCommPorts()[port];
        TerminalTextArea.append("attempting to open " +  comPorts[port].getDescriptivePortName() + "\n");
        if(!comPort.openPort()) 
           { TerminalTextArea.append("failed to open COM port " + comPorts[port].getDescriptivePortName() + "\n"); port=-1; return; }
        TerminalTextArea.append("Opened COM port " + comPorts[port].getDescriptivePortName() + " OK\n");
        comPort.setBaudRate(115200);
        comPort.addDataListener(new SerialPortDataListener() {
          @Override
          public int getListeningEvents() { return SerialPort.LISTENING_EVENT_DATA_AVAILABLE; }
          @Override
          // character received by serial port - read and dispay in TextArea
          public void serialEvent(SerialPortEvent event)
            {
            if (event.getEventType() != SerialPort.LISTENING_EVENT_DATA_AVAILABLE)  return;
            while(comPort.bytesAvailable() > 0)
                {
                byte[] newData = new byte[1];
                int numRead = comPort.readBytes(newData, 1);//newData.length);
                // append text to textarea and move to end (required for Linux?)
                TerminalTextArea.append(new String(newData));
                 if(newData.length>0 && newData[0]=='>') CanbusData=true;
                if(CanbusData)     canbusReceivedMessageTextBox.append(new String(newData));
                if(newData.length>0 && newData[0]=='\n') CanbusData=false;
                }
            int l=TerminalTextArea.getText().length();
            TerminalTextArea.setSelectionStart(l);
            TerminalTextArea.setSelectionEnd(l);
        }
        });
        }      


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CanbusSpeedButtonGroup = new javax.swing.ButtonGroup();
        TerminalTextArea = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        transmitButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        canbusIDtextField1 = new java.awt.TextField();
        RTRcheckBox = new javax.swing.JCheckBox();
        extended29bitIDcheckBox = new javax.swing.JCheckBox();
        canbusMessageTextBox = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        CanbusSpeedPanel = new javax.swing.JPanel();
        Button250 = new javax.swing.JRadioButton();
        Button125 = new javax.swing.JRadioButton();
        Button500 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        CanbusSetupPanel = new javax.swing.JPanel();
        CanbusSetButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        RFX0checkBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CANBUSfilterRXF0_2textBox = new java.awt.TextField();
        CANBUSfilterRXF0_1textBox = new java.awt.TextField();
        CANBUSmaskRFX0textBox = new java.awt.TextField();
        jPanel4 = new javax.swing.JPanel();
        RFX1checkBox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CANBUSfilterRXF1_2textBox = new java.awt.TextField();
        CANBUSfilterRXF1_1textBox = new java.awt.TextField();
        CANBUSmaskRFX1textBox = new java.awt.TextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CANBUSfilterRXF1_4textBox = new java.awt.TextField();
        CANBUSfilterRXF1_3textBox = new java.awt.TextField();
        canbusReceivedMessageTextBox = new java.awt.TextArea();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java - Arduino Canbus monitor");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N

        TerminalTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        TerminalTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TerminalTextAreaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("serial data received");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Canbus received and transmitted messages");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Java - Arduino Canbus Monitor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        transmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transmitButton.setText("transmit message");
        transmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmitButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("message ID (hex)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("message (hex)");

        canbusIDtextField1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        canbusIDtextField1.setText("0");
        canbusIDtextField1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        RTRcheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RTRcheckBox.setText("RTR");

        extended29bitIDcheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        extended29bitIDcheckBox.setText("Extended 29bit ID");

        canbusMessageTextBox.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        canbusMessageTextBox.setText("0");
        canbusMessageTextBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusMessageTextBoxTextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canbusIDtextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canbusMessageTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(extended29bitIDcheckBox)
                .addGap(86, 86, 86)
                .addComponent(RTRcheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extended29bitIDcheckBox)
                    .addComponent(RTRcheckBox))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(canbusIDtextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(canbusMessageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transmitButton)
                        .addGap(33, 33, 33))))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Canbus Setup");

        CanbusSpeedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CanbusSpeedButtonGroup.add(Button250);
        Button250.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button250.setSelected(true);
        Button250.setText("250kbs");
        Button250.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupCanbus(evt);
            }
        });

        CanbusSpeedButtonGroup.add(Button125);
        Button125.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button125.setText("125kbs");
        Button125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupCanbus(evt);
            }
        });

        CanbusSpeedButtonGroup.add(Button500);
        Button500.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Button500.setText("500kbs");
        Button500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupCanbus(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("speed");

        javax.swing.GroupLayout CanbusSpeedPanelLayout = new javax.swing.GroupLayout(CanbusSpeedPanel);
        CanbusSpeedPanel.setLayout(CanbusSpeedPanelLayout);
        CanbusSpeedPanelLayout.setHorizontalGroup(
            CanbusSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanbusSpeedPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(Button125)
                .addGap(30, 30, 30)
                .addComponent(Button250)
                .addGap(26, 26, 26)
                .addComponent(Button500)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        CanbusSpeedPanelLayout.setVerticalGroup(
            CanbusSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanbusSpeedPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(CanbusSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Button125)
                    .addComponent(Button250)
                    .addComponent(Button500))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        CanbusSetupPanel.setBackground(new java.awt.Color(255, 255, 255));
        CanbusSetupPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CanbusSetButton.setText("set");
        CanbusSetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupCanbus(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        RFX0checkBox.setBackground(new java.awt.Color(255, 255, 255));
        RFX0checkBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RFX0checkBox.setText("extended 29-bit ID (else standard 11-bit ID) ");
        RFX0checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFX0checkBoxActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("receiver 0 filter 2 (hex)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("receiver 0 mask (hex)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("receiver 0 filter 1 (hex)");

        CANBUSfilterRXF0_2textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF0_2textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        CANBUSfilterRXF0_1textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF0_1textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        CANBUSmaskRFX0textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSmaskRFX0textBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANBUSmaskRFX0textBoxActionPerformed(evt);
            }
        });
        CANBUSmaskRFX0textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(RFX0checkBox))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CANBUSmaskRFX0textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANBUSfilterRXF0_1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANBUSfilterRXF0_2textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(RFX0checkBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(CANBUSmaskRFX0textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(CANBUSfilterRXF0_1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CANBUSfilterRXF0_2textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        RFX1checkBox.setBackground(new java.awt.Color(255, 255, 255));
        RFX1checkBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RFX1checkBox.setText("extended 29-bit ID (else standard 11-bit ID) ");
        RFX1checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFX1checkBoxActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("receiver 1 filter 2 (hex)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("receiver 1 mask (hex)");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("receiver 1 filter 1 (hex)");

        CANBUSfilterRXF1_2textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF1_2textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        CANBUSfilterRXF1_1textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF1_1textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        CANBUSmaskRFX1textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSmaskRFX1textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("receiver 1 filter 4 (hex)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("receiver 1 filter 3 (hex)");

        CANBUSfilterRXF1_4textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF1_4textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        CANBUSfilterRXF1_3textBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CANBUSfilterRXF1_3textBox.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                canbusIDtextField1TextValueChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(RFX1checkBox))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CANBUSmaskRFX1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANBUSfilterRXF1_1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CANBUSfilterRXF1_2textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CANBUSfilterRXF1_3textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CANBUSfilterRXF1_4textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(RFX1checkBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(CANBUSmaskRFX1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CANBUSfilterRXF1_1textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CANBUSfilterRXF1_2textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CANBUSfilterRXF1_3textBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CANBUSfilterRXF1_4textBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout CanbusSetupPanelLayout = new javax.swing.GroupLayout(CanbusSetupPanel);
        CanbusSetupPanel.setLayout(CanbusSetupPanelLayout);
        CanbusSetupPanelLayout.setHorizontalGroup(
            CanbusSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanbusSetupPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CanbusSetButton)
                .addGap(18, 18, 18)
                .addGroup(CanbusSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        CanbusSetupPanelLayout.setVerticalGroup(
            CanbusSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CanbusSetupPanelLayout.createSequentialGroup()
                .addGroup(CanbusSetupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CanbusSetupPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CanbusSetupPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(CanbusSetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(CanbusSpeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CanbusSetupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CanbusSpeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CanbusSetupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        canbusReceivedMessageTextBox.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        canbusReceivedMessageTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                canbusReceivedMessageTextBoxKeyTyped(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(271, 271, 271)
                                .addComponent(jLabel1)
                                .addGap(221, 221, 221))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(canbusReceivedMessageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(TerminalTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TerminalTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canbusReceivedMessageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // key hit in terminal TextArea - transmit to serial port if open
    private void TerminalTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TerminalTextAreaKeyTyped
  /*      if(comPort != null && comPort.isOpen())
            comPort.writeBytes( new byte[]{(byte) evt.getKeyChar()},  1);
        else
            TerminalTextArea.append(" no COM port open!\n");
         int l=TerminalTextArea.getText().length();
        TerminalTextArea.setSelectionStart(l);
        TerminalTextArea.setSelectionEnd(l);
 */
    }//GEN-LAST:event_TerminalTextAreaKeyTyped

    private void transmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmitButtonActionPerformed
        // TODO add your handling code here:
        //CANBUStransmit(SerialPort serialPort1, int extendedID, int canbusOutputID, int RTR, int[] message)
            StringBuilder sb = new StringBuilder("0000000000000000");
            for(int ii = 0; ii <=  canbusMessageTextBox.getText().length() - 1; ii++)
              sb.setCharAt(ii, canbusMessageTextBox.getText().charAt(ii));                   // copy hex digits to s
            String save = sb.toString();
            canbusMessage = Long.parseUnsignedLong(save, 16);                  // convert s to 64 bit unsigned number
        int[] message={1,2,3,4,5,6,7,8};
        int i  = 7;
        while (i >= 0 )         // convert 64bit number into 8 byte values
        {
            Long x = new Long(0xFF);
            try
               { message[i] = (int)(canbusMessage & x); }      // get rightmost byte
            catch (Exception e) { }
            canbusMessage = canbusMessage >> 8 ;                        // shift right one byte
            i = i - 1 ;                                                 // get next byte
        }
       int RTR=0,extendedID=0;
        if (RTRcheckBox.isSelected()) RTR = 1; else RTR = 0;
                if (extended29bitIDcheckBox.isSelected()) extendedID = 1; else extendedID = 0;

        CANBUStransmit(comPort, extendedID, canbusTranmitID, RTR, message);
    }
    
        {
    }//GEN-LAST:event_transmitButtonActionPerformed
    private Integer canbusTranmitID=0, Rx0mask=0, Rx1mask=0;
    private Long canbusMessage=0L;
    private Integer[] Rx0filter={0, 0},  Rx1filter={0, 0, 0, 0};
    private void canbusIDtextField1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_canbusIDtextField1TextValueChanged
        canbusTranmitID=read11or29bitHexNumber(canbusIDtextField1, canbusTranmitID, extended29bitIDcheckBox.isSelected());
        System.out.println("canbusTranmitID" + canbusTranmitID);
        Rx0mask=read11or29bitHexNumber(CANBUSmaskRFX0textBox, Rx0mask, RFX0checkBox.isSelected());
        Rx0filter[0]=read11or29bitHexNumber(CANBUSfilterRXF0_1textBox, Rx0filter[0], RFX0checkBox.isSelected());
        Rx0filter[1]=read11or29bitHexNumber(CANBUSfilterRXF0_2textBox, Rx0filter[1], RFX0checkBox.isSelected());
        Rx1mask=read11or29bitHexNumber(CANBUSmaskRFX1textBox, Rx1mask, RFX1checkBox.isSelected());
        Rx1filter[0]=read11or29bitHexNumber(CANBUSfilterRXF1_1textBox, Rx1filter[0], RFX1checkBox.isSelected());
        Rx1filter[1]=read11or29bitHexNumber(CANBUSfilterRXF1_2textBox, Rx1filter[1], RFX1checkBox.isSelected());
        Rx1filter[2]=read11or29bitHexNumber(CANBUSfilterRXF1_3textBox, Rx1filter[2], RFX1checkBox.isSelected());
        Rx1filter[3]=read11or29bitHexNumber(CANBUSfilterRXF1_4textBox, Rx1filter[3], RFX1checkBox.isSelected());

    }//GEN-LAST:event_canbusIDtextField1TextValueChanged

    private void canbusMessageTextBoxTextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_canbusMessageTextBoxTextValueChanged
        canbusMessage=  read64bitHexNumber(canbusMessageTextBox, canbusMessage);
        String l1Str = Long.toUnsignedString(canbusMessage, 16);
        System.out.println("canbusMessage " + l1Str);
        l1Str = Long.toUnsignedString(canbusMessage, 10);
        System.out.println("canbusMessage " + l1Str);

    }//GEN-LAST:event_canbusMessageTextBoxTextValueChanged

    private void canbusReceivedMessageTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canbusReceivedMessageTextBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_canbusReceivedMessageTextBoxKeyTyped

    public void serialTransmit(String s)
    {
             byte[] b= s.getBytes();
            if(comPort != null && comPort.isOpen())
                comPort.writeBytes(b, b.length);
       
    }
    public  void CANBUStransmit(SerialPort serialPort1, int extendedID, int canbusOutputID, int RTR, int[] message)
        {
            String s=CANBUStransmit + " " + canbusOutputID
                       + " " + extendedID + " " + RTR
                       + " " + message[0] + " " + message[1] + " " + message[2] + " " + message[3]
                       + " " + message[4] + " " + message[5] + " " + message[6] + " " + message[7] + "\n";
            //TerminalTextArea.append("\n"+s+"\n");
            byte[] b= s.getBytes();
            if(comPort != null && comPort.isOpen())
                comPort.writeBytes(b, b.length);
       }
    
    private void setupCanbus(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupCanbus
         System.out.println("setup canbus");
         int CANBUSspeed1 = 500, Rx0extended, Rx1extended;
        if (Button125.isSelected())   CANBUSspeed1 = 125;          // setup canbus speed 
        else
            if (Button250.isSelected())  CANBUSspeed1 = 250; 
        if (RFX0checkBox.isSelected()) Rx0extended = 1; else Rx0extended = 0;
        if (RFX1checkBox.isSelected()) Rx1extended = 1; else Rx1extended = 0;

        serialTransmit(CANBUSspeed + " " + CANBUSspeed1 + "\n");
        serialTransmit(Rx0maskF + " " + +Rx0extended + " " + Rx0mask + "\n");
        serialTransmit(Rx1maskF + " " + +Rx1extended + " " + Rx1mask  + "\n");
        serialTransmit(Rx0filter1 + " " + +Rx0extended + " " + Rx0filter[0]  + "\n");
        serialTransmit(Rx0filter2 + " " + +Rx0extended + " " + Rx0filter[1]  + "\n");
        serialTransmit(Rx1filter3 + " " + +Rx1extended + " " + Rx1filter[0]  + "\n");
        serialTransmit(Rx1filter4 + " " + +Rx1extended + " " + Rx1filter[1]  + "\n");
        serialTransmit(Rx1filter5 + " " + +Rx1extended + " " + Rx1filter[2]  + "\n");
        serialTransmit(Rx1filter6 + " " + +Rx1extended + " " + Rx1filter[3] + "\n");
      
         
      // TODO add your handling code here:
    }//GEN-LAST:event_setupCanbus

    private void RFX1checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFX1checkBoxActionPerformed
          if (RFX1checkBox.isSelected()) CANBUSmaskRFX1textBox.setText("1fffffff");
          else CANBUSmaskRFX1textBox.setText("7ff");
          CANBUSfilterRXF1_1textBox.setText("0"); CANBUSfilterRXF1_2textBox.setText("0");
          CANBUSfilterRXF1_3textBox.setText("0"); CANBUSfilterRXF1_4textBox.setText("0"); 

    }//GEN-LAST:event_RFX1checkBoxActionPerformed

    private void RFX0checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFX0checkBoxActionPerformed
         if (RFX0checkBox.isSelected()) CANBUSmaskRFX0textBox.setText("1fffffff");
            else CANBUSmaskRFX0textBox.setText("7ff");
         CANBUSfilterRXF0_1textBox.setText("0"); CANBUSfilterRXF0_2textBox.setText("0"); 

    }//GEN-LAST:event_RFX0checkBoxActionPerformed

    private void CANBUSmaskRFX0textBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANBUSmaskRFX0textBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CANBUSmaskRFX0textBoxActionPerformed

    // @param args the command line arguments
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jTerminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jTerminal().setVisible(true);
            }
        });
    }

       // canbus commands to Arduino
       public static final int CANBUSspeed=0, CANBUStransmit=1, Rx0maskF=2, Rx0filter1=3, Rx0filter2=4,
            Rx1maskF=5, Rx1filter3=6, Rx1filter4=7, Rx1filter5=8, Rx1filter6=9;
     

       // read a unsigned 11bit or 29bit hex number (canbus ID) from TextBox, if not hex reject it, write number back to text box
        private int read11or29bitHexNumber(TextField textbox, Integer number, boolean extended)
        {
            Integer numberSaved=number;
            if (textbox.equals(""))                      // if TextBox is empty value is 0
                number = 0;
            else                                         // else convert string to hex
                try
                {
                    int ID = Integer.parseUnsignedInt(textbox.getText(), 16);
                    System.out.println("ID " + ID);
                    if (extended)
                        { if (ID <= 0x1FFFFFFF) number = ID; else  numberSaved=0; } // if > 29bit reject it
                    else
                        { if (ID <= 0x7ff) number = ID;  else  numberSaved=0;  }// if > 11bit reject it
                }
                catch (Exception e) { numberSaved=0; }
            //Console.WriteLine("number {0:X}", number);
            if(! numberSaved.equals(number) )
                textbox.setText((Integer.toHexString(number)).toUpperCase());    // write number back out to TextBox
            //System.out.println("textfield " + textbox.getText());
            //System.out.println("number " + number);
            textbox.setSelectionStart( 100);
            textbox.setSelectionEnd( 100);
            return number;
        }
        
        // read a unsigned 64bit hex number (canbus ID) from TextBox, if not hex reject it, write number back to text box
        private boolean parsedTextField=false;
        private Long read64bitHexNumber(TextField textbox, Long number)
        {
            if(parsedTextField) { parsedTextField=false; return number; }
            parsedTextField=true;
            if (textbox.equals(""))                 // if TextBox is empty value is 0
                number = 0L;
            else 
              if(textbox.getText().length() <=16)   // maximum 16 characters
                try                                 // convert string to hex
                {
                    Long ID = Long.parseUnsignedLong(textbox.getText(), 16);
                    number = ID;  
                }
                catch (Exception e) { }
            String l1Str = (Long.toUnsignedString(number, 16)).toUpperCase();
            textbox.setText(l1Str);    // write number back out to TextBox
            textbox.setSelectionStart( 100);
            textbox.setSelectionEnd( 100);
            return number;
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Button125;
    private javax.swing.JRadioButton Button250;
    private javax.swing.JRadioButton Button500;
    private java.awt.TextField CANBUSfilterRXF0_1textBox;
    private java.awt.TextField CANBUSfilterRXF0_2textBox;
    private java.awt.TextField CANBUSfilterRXF1_1textBox;
    private java.awt.TextField CANBUSfilterRXF1_2textBox;
    private java.awt.TextField CANBUSfilterRXF1_3textBox;
    private java.awt.TextField CANBUSfilterRXF1_4textBox;
    private java.awt.TextField CANBUSmaskRFX0textBox;
    private java.awt.TextField CANBUSmaskRFX1textBox;
    private javax.swing.JButton CanbusSetButton;
    private javax.swing.JPanel CanbusSetupPanel;
    private javax.swing.ButtonGroup CanbusSpeedButtonGroup;
    private javax.swing.JPanel CanbusSpeedPanel;
    private javax.swing.JCheckBox RFX0checkBox;
    private javax.swing.JCheckBox RFX1checkBox;
    private javax.swing.JCheckBox RTRcheckBox;
    private java.awt.TextArea TerminalTextArea;
    private java.awt.TextField canbusIDtextField1;
    private java.awt.TextField canbusMessageTextBox;
    private java.awt.TextArea canbusReceivedMessageTextBox;
    private javax.swing.JCheckBox extended29bitIDcheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton transmitButton;
    // End of variables declaration//GEN-END:variables
}
